name: Deploy

on:
  push:
    branches:
      - main
      - docker-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend
        run: ./gradlew clean shadowJar

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t oliverschlueter/istream:latest .

      - name: Publish Docker Image
        run: docker push oliverschlueter/istream:latest
